Add param checks to manual entry

diff --git a/trk b/trk
--- a/trk
+++ b/trk
@@ -199,6 +199,15 @@ add_entry() {
     local entry_name="$1"
     local time_interval="$2"
 
+    if [ -z "$entry_name" ]; then
+        echo "missing entry_name"
+        exit 1
+    fi
+    if [ -z "$time_interval" ]; then
+        echo "missing time_interval"
+        exit 1
+    fi
+
     local now=`get_timestamp`
 
     stop_time=`date -d "$time_interval" '+%s'`
